Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/ecology-textbook/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/anaconda3/envs/ecology-textbook/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/anaconda3/envs/ecology-textbook/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/anaconda3/envs/ecology-textbook/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/anaconda3/envs/ecology-textbook/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/anaconda3/envs/ecology-textbook/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/usr/local/anaconda3/envs/ecology-textbook/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/anaconda3/envs/ecology-textbook/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(ggrepel))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(magrittr))

###Figure 11.2
#Set variables
r=1.9; #Growth rate.
t0=0; t1=1000; #Time boundaries.
r1=r-1; r2=-1; s12=-r; #Parameters.
N1=.5; N2=.1; t=0; dt=1; #Initial conditions.
x.vec <- c(N1) ; y.vec <- c(N2) ; t.vec <- c(t) #Vectors for recording

#Iterate the system from t0 to t1
while(t<=t0+t1) {
  #Calculate coupling
  s21=1/N2;
  #Calculate change in N1 and N2
  dN1=N1*(r1+s12*N2)*dt;
  dN2=N2*(r2+s21*N1)*dt;
  #Calculate new N1 and N2 values
  N1=N1+dN1; N2=N2+dN2; t=t+dt;
  #Record these values
  x.vec <- c(x.vec,N1)
  y.vec <- c(y.vec,N2)
  t.vec <- c(t.vec,t)
}

#Make data frames for plotting
data <- data.frame(N1=x.vec,N2=y.vec,t=t.vec)
labels <- data %>% subset(t < (t0+13))
labels$t <- paste0("t = ",labels$t)

#Plot
plot.n <- data %>%
  ggplot(aes(x=N1, y=N2, label=t)) +
  geom_point(size=1, colour="#4287f5") +
  geom_segment(aes(xend=c(tail(N1, n=-1), NA),yend=c(tail(N2, n=-1), NA)),
               colour="#4287f5",size=1,arrow=arrow(length=unit(0.3,"cm"))) +
#  geom_text_repel(data=labels,fontface="bold") +
  theme_light() +
  scale_x_continuous(limits=c(0,1),breaks=seq(from=0,to=1,by=0.2),expand=c(0,0)) +
  scale_y_continuous(limits=c(0,1),breaks=seq(from=0,to=1,by=0.2),expand=c(0,0)) +
  theme(panel.border = element_rect(colour="black"),
        axis.ticks=element_line(colour="black"),
        axis.ticks.length = unit(8,"pt"))

suppressWarnings(plot(plot.n))
------------------

Error in library(ggrepel): there is no package called ‘ggrepel’
Traceback:

1. suppressPackageStartupMessages(library(ggrepel))
2. withCallingHandlers(expr, packageStartupMessage = function(c) tryInvokeRestart("muffleMessage"))
3. library(ggrepel)
ERROR: Error in library(ggrepel): there is no package called ‘ggrepel’


