Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/ecology-textbook/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/anaconda3/envs/ecology-textbook/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/anaconda3/envs/ecology-textbook/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/anaconda3/envs/ecology-textbook/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/anaconda3/envs/ecology-textbook/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/anaconda3/envs/ecology-textbook/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/usr/local/anaconda3/envs/ecology-textbook/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/anaconda3/envs/ecology-textbook/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
render:
  image:
    width: 600px
    alt: fig_4_3
    classes: shadow bg-primary
  figure:
    caption: |      
      Logistic growth contrasted with orthologistic growth and exponential growth. 
    name: fig_4_2 
tags: ["hide_input"]  
---
pivot_longer(population, !time, names_to = "growth type", values_to = "N") %>%
  ggplot(aes(x=time, y=N, color=`growth type`)) + geom_point() + geom_line() + 
  coord_cartesian(ylim=c(0, 1100), xlim=c(0,11)) + #limits of x and y axis, allows for out of bounds line
  scale_color_manual(values = c("blue", "yellow","red")) +
  xlab("t") + #label for x axis
  ylab("N(t)") + #label for y axis
  scale_x_continuous(breaks=c(0,1,2,3,4,5,6,7,8,9,10)) + #tick labels for x axis
  scale_y_continuous(breaks=c(0,250,500,750,1000)) #tick labels for y axis
------------------

Error in parse(text = x, srcfile = src): <text>:3:15: unexpected symbol
2:   image:
3:     width: 600px
                 ^
Traceback:

ERROR: Error in parse(text = x, srcfile = src): <text>:3:15: unexpected symbol
2:   image:
3:     width: 600px
                 ^


